### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/mailwatch-install-script#2]
Previous discussion in [https://github.com/mailwatch/1.2.0/pull/512](https://github.com/mailwatch/1.2.0/pull/512)

- [ ] apache 2.2/2.4
  - [x] RedHat/CentOS (to test)
  - [x] Debian/Ubuntu (Skywalker-11/stefaweb)
  - [ ] SUSE (to test)
- [ ] nginx 
  - [ ] RedHat/CentOS
  - [ ] Debian/Ubuntu (stefaweb)
  - [ ] SUSE
- [ ] sendmail
  - [ ] RedHat/CentOS
  - [ ] Debian/Ubuntu
  - [ ] SUSE 
- [ ] postfix
  - [x] RedHat/CentOS (asuweb)
  - [x] Debian/Ubuntu (stefaweb)
  - [ ] SUSE  (to test)
- [ ] exim 
  - [ ] RedHat/CentOS  (to test)
  - [x] Debian/Ubuntu (stefaweb)
  - [ ] SUSE  (to test)
- [ ] find paths, users/groups, commands for different os
  - [x] RedHat/CentOS (asuweb)
  - [x] Debian/Ubuntu (Skywalker-11/stefaweb)
  - [ ] SUSE  (to test)
- [x] (optional) auto detect os
- [ ] (optional) detect old install and perform needed updates while keeping old data
  - [x] keep database
  - [x] keep config file
  - [ ]  mta config, web server updates?
- [ ] test if db exists, ask for confirmation to override

**Comment by stefaweb** [comment]
I post the tree if this can help.

```
mailwatch/
├── setup
│   ├── deb
│   │   ├── apache.sh
│   │   ├── apache2
│   │   │   └── conf-available
│   │   │       └── mailwatch.conf
│   │   ├── cron_crontab.sh
│   │   ├── exim
│   │   │   └── etc
│   │   │       ├── default
│   │   │       │   └── exim
│   │   │       └── exim
│   │   │           ├── conf.d
│   │   │           │   └── main
│   │   │           │       ├── 00_mailscanner_listmacrosdefs
│   │   │           │       └── 01_mailscanner_config
│   │   │           ├── hubbed_hosts
│   │   │           ├── mailscanner_acldefs
│   │   │           └── relay_domains
│   │   ├── exim.sh
│   │   ├── mailscanner
│   │   │   └── etc
│   │   │       └── MailScanner
│   │   │           └── conf.d
│   │   │               └── mailwatch.conf
│   │   ├── mailscanner.sh
│   │   ├── postfix
│   │   │   └── etc
│   │   │       └── postfix
│   │   │           └── header_checks
│   │   └── postfix.sh
│   └── rpm
│       ├── apache
│       │   └── conf.d
│       │       └── mailwatch.conf
│       ├── apache.sh
│       ├── cron_crontab.sh
│       ├── exim
│       │   └── etc
│       │       └── exim
│       │           └── ?
│       ├── exim.sh
│       ├── mailscanner
│       │   └── etc
│       │       └── MailScanner
│       │           └── conf.d
│       │               └── mailwatch.conf
│       ├── mailscanner.sh
│       └── postfix
│           └── etc
│               └── postfix
│                   └── header_checks
└── setup.sh
```

[mailwatch.zip](https://github.com/mailwatch/mailwatch-install-script/files/774216/mailwatch.zip)

**Comment by stefaweb** [comment]
I can close?

**Comment by Skywalker-11** [comment]
As the todo list is not finished yet we should let it open

**Comment by stefaweb** [comment]
It was a mistake. I clicked without looking on my keyboard. ;)

But, on the mailwatch repository, I can delete only my own Issue. Why?

**Comment by Skywalker-11** [comment]
Permissions set by Manuel

**Comment by stefaweb** [comment]
I'm very sorry. Done a big mistake. I deleted "develop".

You should reduce my right.

**Comment by Skywalker-11** [comment]
lol 🤣

**Comment by stefaweb** [comment]
Ouf, you reverted it back. I was afraid that all was lost.
Manuel should absolute reduce my right as in the mailwatch project.

**Comment by stefaweb** [comment]
I forgot for Exim Debian.

Before /usr/sbin/update-exim4.conf add:

hostname --fqdn in /etc/mailname

(put host.domain.tld in the file /etc/mailname)

**Comment by remkolodder** [comment]
Stuff in FreeBSD is configured in /usr/local/{etc,bin,share/doc}, so that is somewhat of a change.
But honestly do we need to do all that?

If we describe that properly on an install page, then people should find that out themselves. I mean if they cannot configure a system, why would they be running it in the first place. At some point in time that will either bite the company or us (us=project mailwatch).

I was more thinking of a 'install.php' which lets you set the database parameters, lets you set certain parameters to get the installation going (like timezone, quarantine report information, etc), and after acknowledging the proper database is created and filled with the available information, next to a conf.php which is written via install.php (and/or can be made copy/paste for systems where you cannot write to conf.php for whatever reason).

I do not think we should setup an entire system, integrating mailwatch and mailscanner for example, can be different for every single individual, with many many different MTA's and setups. You do not want to cover that. You want to make sure that if the prereqs are met, mailwatch can be used by the end user..

But that is my humble opinion ;-)

**Comment by endelwar** [comment]
> if they cannot configure a system, why would they be running it in the first place. At some point in time that will either bite the company or us (us=project mailwatch)

🍻🍻🍻🍻🍻

**Comment by Skywalker-11** [comment]
I already thought on putting the part that configures MailWatch itself to a seperate file so you can condigure every part of the large script itself. I'll try to do that soon maybe this weekend
